// This file was generated by the Supabase MCP server.
// It contains the TypeScript types for your project schema.

export type Json =
    | string
    | number
    | boolean
    | null
    | { [key: string]: Json | undefined }
    | Json[]

export interface Database {
    public: {
        Tables: {
            applications: {
                Row: {
                    answers: Json | null
                    city: string | null
                    college: string | null
                    created_at: string
                    daily_availability: string | null
                    degree: string | null
                    duration: string | null
                    email: string
                    full_name: string
                    id: string
                    mobile: string
                    mode: string | null
                    registration_no: string | null
                    resume_link: string | null
                    role_title: string
                    start_date: string | null
                    status: string | null
                    year: string | null
                }
                Insert: {
                    answers?: Json | null
                    city?: string | null
                    college?: string | null
                    created_at?: string
                    daily_availability?: string | null
                    degree?: string | null
                    duration?: string | null
                    email: string
                    full_name: string
                    id?: string
                    mobile: string
                    mode?: string | null
                    registration_no?: string | null
                    resume_link?: string | null
                    role_title: string
                    start_date?: string | null
                    status?: string | null
                    year?: string | null
                }
                Update: {
                    answers?: Json | null
                    city?: string | null
                    college?: string | null
                    created_at?: string
                    daily_availability?: string | null
                    degree?: string | null
                    duration?: string | null
                    email?: string
                    full_name?: string
                    id?: string
                    mobile?: string
                    mode?: string | null
                    registration_no?: string | null
                    resume_link?: string | null
                    role_title?: string
                    start_date?: string | null
                    status?: string | null
                    year?: string | null
                }
                Relationships: []
            }
            bookings: {
                Row: {
                    answers: Json | null
                    created_at: string
                    date: string
                    email: string | null
                    file_url: string | null
                    id: string
                    name: string | null
                    phone: string | null
                    status: string | null
                    subject: string | null
                    time: string
                }
                Insert: {
                    answers?: Json | null
                    created_at?: string
                    date: string
                    email?: string | null
                    file_url?: string | null
                    id?: string
                    name?: string | null
                    phone?: string | null
                    status?: string | null
                    subject?: string | null
                    time: string
                }
                Update: {
                    answers?: Json | null
                    created_at?: string
                    date?: string
                    email?: string | null
                    file_url?: string | null
                    id?: string
                    name?: string | null
                    phone?: string | null
                    status?: string | null
                    subject?: string | null
                    time?: string
                }
                Relationships: []
            }
            courses: {
                Row: {
                    created_at: string
                    description: string | null
                    id: string
                    price: number | null
                    published: boolean | null
                    thumbnail_url: string | null
                    title: string
                }
                Insert: {
                    created_at?: string
                    description?: string | null
                    id?: string
                    price?: number | null
                    published?: boolean | null
                    thumbnail_url?: string | null
                    title: string
                }
                Update: {
                    created_at?: string
                    description?: string | null
                    id?: string
                    price?: number | null
                    published?: boolean | null
                    thumbnail_url?: string | null
                    title?: string
                }
                Relationships: []
            }
            enrollments: {
                Row: {
                    course_id: string
                    enrolled_at: string
                    user_id: string
                }
                Insert: {
                    course_id: string
                    enrolled_at?: string
                    user_id: string
                }
                Update: {
                    course_id?: string
                    enrolled_at?: string
                    user_id?: string
                }
                Relationships: [
                    {
                        foreignKeyName: "enrollments_course_id_fkey"
                        columns: ["course_id"]
                        referencedRelation: "courses"
                        referencedColumns: ["id"]
                    },
                    {
                        foreignKeyName: "enrollments_user_id_fkey"
                        columns: ["user_id"]
                        referencedRelation: "users"
                        referencedColumns: ["id"]
                    }
                ]
            }
            lessons: {
                Row: {
                    course_id: string
                    created_at: string
                    description: string | null
                    duration: string | null
                    id: string
                    position: number
                    title: string
                    video_url: string | null
                }
                Insert: {
                    course_id: string
                    created_at?: string
                    description?: string | null
                    duration?: string | null
                    id?: string
                    position: number
                    title: string
                    video_url?: string | null
                }
                Update: {
                    course_id?: string
                    created_at?: string
                    description?: string | null
                    duration?: string | null
                    id?: string
                    position?: number
                    title?: string
                    video_url?: string | null
                }
                Relationships: [
                    {
                        foreignKeyName: "lessons_course_id_fkey"
                        columns: ["course_id"]
                        referencedRelation: "courses"
                        referencedColumns: ["id"]
                    }
                ]
            }
            profiles: {
                Row: {
                    created_at: string
                    email: string | null
                    id: string
                    role: string | null
                }
                Insert: {
                    created_at?: string
                    email?: string | null
                    id: string
                    role?: string | null
                }
                Update: {
                    created_at?: string
                    email?: string | null
                    id?: string
                    role?: string | null
                }
                Relationships: [
                    {
                        foreignKeyName: "profiles_id_fkey"
                        columns: ["id"]
                        referencedRelation: "users"
                        referencedColumns: ["id"]
                    }
                ]
            }
            progress: {
                Row: {
                    is_completed: boolean | null
                    lesson_id: string
                    updated_at: string
                    user_id: string
                    watched_time: number | null
                }
                Insert: {
                    is_completed?: boolean | null
                    lesson_id: string
                    updated_at?: string
                    user_id: string
                    watched_time?: number | null
                }
                Update: {
                    is_completed?: boolean | null
                    lesson_id?: string
                    updated_at?: string
                    user_id?: string
                    watched_time?: number | null
                }
                Relationships: [
                    {
                        foreignKeyName: "progress_lesson_id_fkey"
                        columns: ["lesson_id"]
                        referencedRelation: "lessons"
                        referencedColumns: ["id"]
                    },
                    {
                        foreignKeyName: "progress_user_id_fkey"
                        columns: ["user_id"]
                        referencedRelation: "users"
                        referencedColumns: ["id"]
                    }
                ]
            }
        }
        Views: {
            [_ in never]: never
        }
        Functions: {
            [_ in never]: never
        }
        Enums: {
            [_ in never]: never
        }
        CompositeTypes: {
            [_ in never]: never
        }
    }
}
